// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/rs/zerolog"
	"github.com/smartcontractkit/branch-out/github"
	"github.com/smartcontractkit/branch-out/golang"
	mock "github.com/stretchr/testify/mock"
)

// NewGithubIClient creates a new instance of GithubIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGithubIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GithubIClient {
	mock := &GithubIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GithubIClient is an autogenerated mock type for the IClient type
type GithubIClient struct {
	mock.Mock
}

type GithubIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GithubIClient) EXPECT() *GithubIClient_Expecter {
	return &GithubIClient_Expecter{mock: &_m.Mock}
}

// QuarantineTests provides a mock function for the type GithubIClient
func (_mock *GithubIClient) QuarantineTests(ctx context.Context, l zerolog.Logger, repoURL string, targets []golang.QuarantineTarget, options ...github.QuarantineOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, l, repoURL, targets, options)
	} else {
		tmpRet = _mock.Called(ctx, l, repoURL, targets)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QuarantineTests")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, zerolog.Logger, string, []golang.QuarantineTarget, ...github.QuarantineOption) error); ok {
		r0 = returnFunc(ctx, l, repoURL, targets, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GithubIClient_QuarantineTests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuarantineTests'
type GithubIClient_QuarantineTests_Call struct {
	*mock.Call
}

// QuarantineTests is a helper method to define mock.On call
//   - ctx context.Context
//   - l zerolog.Logger
//   - repoURL string
//   - targets []golang.QuarantineTarget
//   - options ...github.QuarantineOption
func (_e *GithubIClient_Expecter) QuarantineTests(ctx interface{}, l interface{}, repoURL interface{}, targets interface{}, options ...interface{}) *GithubIClient_QuarantineTests_Call {
	return &GithubIClient_QuarantineTests_Call{Call: _e.mock.On("QuarantineTests",
		append([]interface{}{ctx, l, repoURL, targets}, options...)...)}
}

func (_c *GithubIClient_QuarantineTests_Call) Run(run func(ctx context.Context, l zerolog.Logger, repoURL string, targets []golang.QuarantineTarget, options ...github.QuarantineOption)) *GithubIClient_QuarantineTests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 zerolog.Logger
		if args[1] != nil {
			arg1 = args[1].(zerolog.Logger)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []golang.QuarantineTarget
		if args[3] != nil {
			arg3 = args[3].([]golang.QuarantineTarget)
		}
		var arg4 []github.QuarantineOption
		var variadicArgs []github.QuarantineOption
		if len(args) > 4 {
			variadicArgs = args[4].([]github.QuarantineOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *GithubIClient_QuarantineTests_Call) Return(err error) *GithubIClient_QuarantineTests_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GithubIClient_QuarantineTests_Call) RunAndReturn(run func(ctx context.Context, l zerolog.Logger, repoURL string, targets []golang.QuarantineTarget, options ...github.QuarantineOption) error) *GithubIClient_QuarantineTests_Call {
	_c.Call.Return(run)
	return _c
}
