// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	jira0 "github.com/andygrunwald/go-jira"
	"github.com/smartcontractkit/branch-out/jira"
	mock "github.com/stretchr/testify/mock"
)

// NewJiraIClient creates a new instance of JiraIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJiraIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *JiraIClient {
	mock := &JiraIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JiraIClient is an autogenerated mock type for the IClient type
type JiraIClient struct {
	mock.Mock
}

type JiraIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *JiraIClient) EXPECT() *JiraIClient_Expecter {
	return &JiraIClient_Expecter{mock: &_m.Mock}
}

// CreateFlakyTestTicket provides a mock function for the type JiraIClient
func (_mock *JiraIClient) CreateFlakyTestTicket(req jira.FlakyTestTicketRequest) (*jira0.Issue, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlakyTestTicket")
	}

	var r0 *jira0.Issue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(jira.FlakyTestTicketRequest) (*jira0.Issue, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(jira.FlakyTestTicketRequest) *jira0.Issue); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jira0.Issue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(jira.FlakyTestTicketRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JiraIClient_CreateFlakyTestTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlakyTestTicket'
type JiraIClient_CreateFlakyTestTicket_Call struct {
	*mock.Call
}

// CreateFlakyTestTicket is a helper method to define mock.On call
//   - req jira.FlakyTestTicketRequest
func (_e *JiraIClient_Expecter) CreateFlakyTestTicket(req interface{}) *JiraIClient_CreateFlakyTestTicket_Call {
	return &JiraIClient_CreateFlakyTestTicket_Call{Call: _e.mock.On("CreateFlakyTestTicket", req)}
}

func (_c *JiraIClient_CreateFlakyTestTicket_Call) Run(run func(req jira.FlakyTestTicketRequest)) *JiraIClient_CreateFlakyTestTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jira.FlakyTestTicketRequest
		if args[0] != nil {
			arg0 = args[0].(jira.FlakyTestTicketRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JiraIClient_CreateFlakyTestTicket_Call) Return(issue *jira0.Issue, err error) *JiraIClient_CreateFlakyTestTicket_Call {
	_c.Call.Return(issue, err)
	return _c
}

func (_c *JiraIClient_CreateFlakyTestTicket_Call) RunAndReturn(run func(req jira.FlakyTestTicketRequest) (*jira0.Issue, error)) *JiraIClient_CreateFlakyTestTicket_Call {
	_c.Call.Return(run)
	return _c
}
