version: 2
pro: false

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/smartcontractkit/branch-out/config.Version={{.Version}}
      - -X github.com/smartcontractkit/branch-out/config.Commit={{.Commit}}
      - -X github.com/smartcontractkit/branch-out/config.BuildTime={{.Date}}
      - -X github.com/smartcontractkit/branch-out/config.BuiltBy=goreleaser
    binary: branch-out

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
