all: false
dir: '{{.InterfaceDir}}'
filename: mocks_test.go
force-file-write: true
formatter: goimports
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/smartcontractkit/branch-out/processing:
    config:
      all: true
