// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package trunk_mock

import (
	"github.com/smartcontractkit/branch-out/jira"
	mock "github.com/stretchr/testify/mock"
)

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

type IClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IClient) EXPECT() *IClient_Expecter {
	return &IClient_Expecter{mock: &_m.Mock}
}

// LinkTicketToTestCase provides a mock function for the type IClient
func (_mock *IClient) LinkTicketToTestCase(testCaseID string, ticket *jira.TicketResponse, repoURL string) error {
	ret := _mock.Called(testCaseID, ticket, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for LinkTicketToTestCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *jira.TicketResponse, string) error); ok {
		r0 = returnFunc(testCaseID, ticket, repoURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IClient_LinkTicketToTestCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkTicketToTestCase'
type IClient_LinkTicketToTestCase_Call struct {
	*mock.Call
}

// LinkTicketToTestCase is a helper method to define mock.On call
//   - testCaseID string
//   - ticket *jira.TicketResponse
//   - repoURL string
func (_e *IClient_Expecter) LinkTicketToTestCase(testCaseID interface{}, ticket interface{}, repoURL interface{}) *IClient_LinkTicketToTestCase_Call {
	return &IClient_LinkTicketToTestCase_Call{Call: _e.mock.On("LinkTicketToTestCase", testCaseID, ticket, repoURL)}
}

func (_c *IClient_LinkTicketToTestCase_Call) Run(run func(testCaseID string, ticket *jira.TicketResponse, repoURL string)) *IClient_LinkTicketToTestCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *jira.TicketResponse
		if args[1] != nil {
			arg1 = args[1].(*jira.TicketResponse)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IClient_LinkTicketToTestCase_Call) Return(err error) *IClient_LinkTicketToTestCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IClient_LinkTicketToTestCase_Call) RunAndReturn(run func(testCaseID string, ticket *jira.TicketResponse, repoURL string) error) *IClient_LinkTicketToTestCase_Call {
	_c.Call.Return(run)
	return _c
}
