// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package trunk_mock

import (
	"github.com/smartcontractkit/branch-out/trunk"
	mock "github.com/stretchr/testify/mock"
)

// NewWebhookEvent creates a new instance of WebhookEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookEvent {
	mock := &WebhookEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebhookEvent is an autogenerated mock type for the WebhookEvent type
type WebhookEvent struct {
	mock.Mock
}

type WebhookEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *WebhookEvent) EXPECT() *WebhookEvent_Expecter {
	return &WebhookEvent_Expecter{mock: &_m.Mock}
}

// GetTestCase provides a mock function for the type WebhookEvent
func (_mock *WebhookEvent) GetTestCase() trunk.TestCase {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTestCase")
	}

	var r0 trunk.TestCase
	if returnFunc, ok := ret.Get(0).(func() trunk.TestCase); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(trunk.TestCase)
	}
	return r0
}

// WebhookEvent_GetTestCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestCase'
type WebhookEvent_GetTestCase_Call struct {
	*mock.Call
}

// GetTestCase is a helper method to define mock.On call
func (_e *WebhookEvent_Expecter) GetTestCase() *WebhookEvent_GetTestCase_Call {
	return &WebhookEvent_GetTestCase_Call{Call: _e.mock.On("GetTestCase")}
}

func (_c *WebhookEvent_GetTestCase_Call) Run(run func()) *WebhookEvent_GetTestCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebhookEvent_GetTestCase_Call) Return(testCase trunk.TestCase) *WebhookEvent_GetTestCase_Call {
	_c.Call.Return(testCase)
	return _c
}

func (_c *WebhookEvent_GetTestCase_Call) RunAndReturn(run func() trunk.TestCase) *WebhookEvent_GetTestCase_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function for the type WebhookEvent
func (_mock *WebhookEvent) GetType() trunk.WebhookType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 trunk.WebhookType
	if returnFunc, ok := ret.Get(0).(func() trunk.WebhookType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(trunk.WebhookType)
	}
	return r0
}

// WebhookEvent_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type WebhookEvent_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *WebhookEvent_Expecter) GetType() *WebhookEvent_GetType_Call {
	return &WebhookEvent_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *WebhookEvent_GetType_Call) Run(run func()) *WebhookEvent_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebhookEvent_GetType_Call) Return(webhookType trunk.WebhookType) *WebhookEvent_GetType_Call {
	_c.Call.Return(webhookType)
	return _c
}

func (_c *WebhookEvent_GetType_Call) RunAndReturn(run func() trunk.WebhookType) *WebhookEvent_GetType_Call {
	_c.Call.Return(run)
	return _c
}
