name: Check for Updated Mocks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-for-updated-mocks:
    name: Check for Updated Mocks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Dependencies
        run: go mod download
      - name: Generate
        run: go generate ./...
      - name: Check for Updated Mocks
        run: git diff --exit-code
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
