name: Release

on:
  push:
    tags:
      - "*"
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-publish:
    permissions:
      contents: read
      id-token: write
    uses: smartcontractkit/.github/.github/workflows/reusable-docker-build-publish.yml@c8bc2e3e0b0ba91253d4cfcba830e31302dd1e4c # June 4, 2025
    with:
      aws-ecr-name: branch-out
      aws-region-ecr: us-west-2
      aws-region-gati: us-west-2
      build-arm64-image: false
      dockerfile: ./Dockerfile
      docker-build-context: .
      docker-manifest-sign: true
      git-sha: ${{ github.sha }}
      github-event-name: ${{ github.event_name }}
      github-ref-name: ${{ github.ref_name }}
      github-ref-type: ${{ github.ref_type}}
      github-workflow-repository: ${{ github.repository }}
      github-runner-amd64: "ubuntu-latest"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      AWS_ROLE_PUBLISH_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_BUILD_PUBLISH }}
